# Site settings
#baseurl = "http://syemialy.github.io/invertise.net"
languageCode = "en-US"
title = "Invertice serves telecommunications industry and is currently performing projects of varying size across the country"
theme = "hugo-agency-theme"


[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Invertice Inc"
	description = "The Invertice has expertise and equipment to install all types of communication towers."


	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "info@invertise.com"


	# Navigation
	[params.navigation]
		brand = "Invertice"
		services = "Services"
		portfolio = "Projects"
		about = "Company"
		contact = "Contact"


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Invertice Inc."
		subtitle = "Telecom Services Provider"
		buttonText = "About Us"


	# Services section
	[params.services]
		title = "Services"
		subtitle = "fast and professional services and confidence"

		[[params.services.list]]
			icon = "fa-wrench"
			title = "Tower Inspections & Services"
			description = "We provide wide variety of inspections and services of fixing faulty items: third party inspection post installation, quality/punch items inspection, foundation inspection, safety climb inspection, tower structure inspection."

		[[params.services.list]]
			icon = "fa-bolt"
			title = "Equipment Installation & Upgrade"
			description = "Our company is a leader on the East market in installing and upgrading Tower/Shelter equipment (starting from cabinets, BBUs, SPDs etc. and finishing with  RHHs, Antennas, A2 Modules."

		[[params.services.list]]
			icon = "fa-align-center"
			title = "Tower Modification & Reinforcement "
			description = "Invertice provides unparalleled quality and an unsurpassed level of professional steel erection and tower modification to our customers. We have experienced AWS fabricators and erectors, as well as certified rigging personnel. Because of that experience, specialized equipment, and unmatched talent we excel at a wide array of projects."

		[[params.services.list]]
			icon = "fa-stethoscope"
			title = "Optimization"
			description = "We are experienced in the Optimization services for any type of Telecom Carrier, those services include: Azimuth measurement and change, MDT & Plumb measurement and changes, RETs set up/troubleshoot, microwave alignment etc."

		[[params.services.list]]
			icon = "fa-stethoscope"
			title = "Testing"
			description = "With high quality of training and experience, up-to-date PIM/Sweep/OTDR gear (our equipment stock has all range of RF Testing equip. – KAELUS, ANRITSU, SunSight etc) our certified (by ANRITSU & KAELUS) climbers and technicians can test modern RF component, troubleshoot & fix any alarm."

		[[params.services.list]]
			icon = "fa-bullseye"
			title = "Decommission & Demolition"
			description = "We strive to provide quick and full decommission services for telecom companies and cell carries. Our decom services include: towers decom, cabinets/rooftop platforms removal, batteries removal/disposal, internal equipment and hazardous materials removal."

		[[params.services.list]]
			icon = "fa-wifi"
			title = "DAS/Small Cell & Microwave dishes"
			description = "Invertice provides services for Distributed Antenna Systems installation, services, upgrade: Indoor/Outdoor DAS systems, Micro sells, Fiber check and install, Integration or Integration assistance."

		[[params.services.list]]
			icon = "fa-wrench"
			title = "Construction management"
			description = "We provide service of supervising construction of tower/tower equipment from the start till the end. Including services on site documentaion (which include drawings readings, SDCO/RFDS reading/explanation, red lines, updates, scope of work and material list close out documents (filling and submitting close out forms, preparing reports, renaming photos, work on the test data)."

		[[params.services.list]]
			icon = "fa-support"
			title = "Civil Construction General Site maintenance services"
			description = "Our in-house technicians are able to support any size ground level project from cabinet installs to complete raw builds. Invertice also provides maintenance of beacon, lightning protection services, compound/access road services, fencing, ground rings, vandalism recovery."
		

	# Portfolio section
	[params.portfolio]
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Projects"
		subtitle = "Invertice serves telecommunications industry and is currently performing projects of varying size across the country."
		text="As one of the top Communication Tower construction company, Invertice has a large amount of projects done.<br/><br/>We are proud to announce all our projects have been successfully finished with 0 accidents occurred on sites and 0 damage done to equipment. For more than 5 years of work and  800+ projects done this is undoubtedly a great achievement.<br/><br/> We were able to reach that thanks to our regular safety meetings/training, our experienced managers and hardworking technician and climbers, that put their soul into work and give their maximum attention to every detail in the documents and on the construction site.<br/><br/> We are partners with:<br/>- ANS<br/>- Black&Veatch<br/>	- Betacom<br/>	- BECHTEL<br/>	- JACOBS<br/>	- NB&C<br/>	- GLOTEL<br/>	- WestTower<br/>	- TELECOM PRO<br/>	- MasTec<br/>	- MUTI<br/>	- CELTONE<br/>	- SBA Towers<br/>	- Crown Castle<br/>	- Centerline<br/><br/>Our Projects included almost all possible types of Tower Construction, including: Rf Equipment upgrades/troubleshooting/change, Tower Reinforcement etc."

		[params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttonText = "Close project"


    # About section
	[params.about]
		title = "Invertice"
		subtitle = "We execute projects of varying size across the US"
		subtitle2 = "How Invertice works"
		endpoint = "Be part<br>of our<br>story!"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "1.jpg"
			date = "Step 1"
			title = "Give us a call"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "2.jpg"
			date = "Step 2"
			title = "Get a Quote"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"

		[[params.about.events]]
			img = "3.jpg"
			date = "Step 3"
			title = "Get your job done"
			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"


	# Client section
	# All the clients' logos are stored under 'static/img/logos'.
	# Replace them with your clients's logos.
	[[params.clients]]
		logo = "att-logo.jpg"
		link = "#"

	# Contact section
	[params.contact]
		title = "Contact us"
		subtitle  = "Lorem ipsum dolor sit amet consectetur."
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
		copyright = "Published under the Apache License 2.0."

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "#"

		[[params.footer.social]]
			icon = "fa-facebook"
			link = "#"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "#"

		[[params.footer.quicklinks]]
			text = "Privacy Policy"
			link = "#"

		[[params.footer.quicklinks]]
			text = "Terms of Use"
			link = "#"
